import { Oswald } from "next/font/google";
import "./globals.css";

const oswaldSans = Oswald({
  variable: "--font-oswald-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${oswaldSans.variable} antialiased bg-slate-800`}
      >
        {children}
      </body>
    </html>
  );
}
